// Padmodaya Campus — Main App Logic
const PRIORITY_COLORS={urgent:{bg:'#FF6B6B',text:'#DC2626',label:'badge-coral'},important:{bg:'#F5A623',text:'#92400E',label:'badge-amber'},normal:{bg:'#4ECDC4',text:'#115E59',label:'badge-teal'}};
let DATA={site:{},notices:[]},CURRENT_FILTER='all';
function escapeHTML(str){return String(str??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function showPage(pageId){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-link').forEach(l=>l.classList.remove('active'));const page=document.getElementById('page-'+pageId);if(page)page.classList.add('active');const link=document.querySelector(`.nav-link[data-page="${pageId}"]`);if(link)link.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});document.getElementById('navLinks').classList.remove('open');}
function toggleMenu(){document.getElementById('navLinks').classList.toggle('open');}
function renderSiteContent(){const s=DATA.site||{},c=s.contact||{};const tag=document.querySelector('.hero-tagline'),desc=document.querySelector('.hero-desc');if(tag)tag.textContent=s.heroTagline||tag.textContent;if(desc)desc.textContent=s.heroDescription||desc.textContent;const a=document.getElementById('aboutText'),m=document.getElementById('missionText'),v=document.getElementById('visionText');if(a)a.textContent=s.about||'';if(m)m.textContent=s.mission||'';if(v)v.textContent=s.vision||'';const rows=document.querySelectorAll('#page-contact .contact-row .contact-value');if(rows.length>=5){rows[0].textContent=c.address||'';rows[1].textContent=c.phone||'';rows[2].textContent=c.mobile1||'';rows[3].textContent=c.mobile2||'';rows[4].textContent=c.email||'';}const links=document.querySelectorAll('#page-contact a.contact-row');if(links.length>=5){if(c.phone)links[0].href='tel:'+c.phone.replace(/[^0-9+]/g,'');if(c.mobile1)links[1].href='tel:+977'+c.mobile1.replace(/[^0-9]/g,'');if(c.mobile2)links[2].href='tel:+977'+c.mobile2.replace(/[^0-9]/g,'');if(c.email)links[3].href='mailto:'+c.email;if(c.facebook)links[4].href=c.facebook;}}
function noticeItemHTML(n){const p=PRIORITY_COLORS[n.priority]||PRIORITY_COLORS.normal;return `<button class="notice-item" data-id="${escapeHTML(n.id)}"><div class="notice-icon-wrap" style="background:${p.bg}15;color:${p.bg}">🔔</div><div class="notice-body"><div style="display:flex;align-items:center;gap:.5rem;flex-wrap:wrap"><div class="notice-title">${escapeHTML(n.title)}</div><span class="badge ${p.label}">${escapeHTML(n.priority)}</span></div><div class="notice-content">${escapeHTML(n.content)}</div><div class="notice-date">📅 ${escapeHTML(n.date)}</div></div><div class="notice-chevron">›</div></button>`;}
function renderNotices(){const order={urgent:3,important:2,normal:1},active=[...DATA.notices].filter(n=>n.active!==false).sort((a,b)=>(order[b.priority]||0)-(order[a.priority]||0)||String(b.date||'').localeCompare(String(a.date||'')));const home=document.getElementById('homeNoticeList');if(home){home.innerHTML=active.slice(0,4).map(noticeItemHTML).join('')||emptyHTML('No notices yet');attachNoticeClickHandlers(home,active.slice(0,4));}const all=document.getElementById('allNoticeList');if(all){const f=CURRENT_FILTER==='all'?active:active.filter(n=>n.priority===CURRENT_FILTER);all.innerHTML=f.map(noticeItemHTML).join('')||emptyHTML('No notices in this category');attachNoticeClickHandlers(all,f);}}
function attachNoticeClickHandlers(c,notices){c.querySelectorAll('.notice-item').forEach(b=>b.addEventListener('click',()=>{const n=notices.find(x=>String(x.id)===String(b.dataset.id));if(n)openNoticeDetail(n);}));}
function emptyHTML(m){return `<div class="empty">🔔<br/><br/>${escapeHTML(m)}</div>`;}
function filterNotices(f){CURRENT_FILTER=f;document.querySelectorAll('.filter-tab').forEach(t=>t.classList.toggle('active',t.dataset.filter===f));renderNotices();}
function attachmentHTML(n,prefix){let h='';if(n.image_url)h+=`<img src="${escapeHTML(n.image_url)}" alt="Notice attachment" style="width:100%;max-height:420px;object-fit:contain;border-radius:12px;margin-top:1rem">`;if(n.file_url)h+=`<p style="margin-top:1rem"><a class="btn btn-secondary btn-sm" href="${escapeHTML(n.file_url)}" target="_blank" rel="noopener">📄 Open ${escapeHTML(n.file_name||'PDF document')}</a></p>`;return h;}
function showLatestNoticePopup(){if(sessionStorage.getItem('notice_dismissed')==='1')return;const order={urgent:3,important:2,normal:1},a=DATA.notices.filter(n=>n.active!==false);if(!a.length)return;const latest=[...a].sort((x,y)=>(order[y.priority]||0)-(order[x.priority]||0)||String(y.date||'').localeCompare(String(x.date||'')))[0],p=PRIORITY_COLORS[latest.priority]||PRIORITY_COLORS.normal;document.getElementById('popupDate').textContent=latest.date;document.getElementById('popupTitle').textContent=latest.title;document.getElementById('popupContent').textContent=latest.content;document.getElementById('popupAttachment').innerHTML=attachmentHTML(latest,'popup');const b=document.getElementById('popupPriority');b.className='badge '+p.label;b.textContent=latest.priority;b.style.display=latest.priority==='normal'?'none':'inline-flex';setTimeout(()=>document.getElementById('noticePopup').classList.add('open'),800);}
function dismissPopup(e){if(e&&e.target&&e.target.closest('.modal'))return;document.getElementById('noticePopup').classList.remove('open');sessionStorage.setItem('notice_dismissed','1');}
function openNoticeDetail(n){const p=PRIORITY_COLORS[n.priority]||PRIORITY_COLORS.normal;document.getElementById('detailDate').textContent=n.date;document.getElementById('detailTitle').textContent=n.title;document.getElementById('detailContent').textContent=n.content;document.getElementById('detailAttachment').innerHTML=attachmentHTML(n,'detail');const b=document.getElementById('detailPriority');b.className='badge '+p.label;b.textContent=n.priority;document.getElementById('noticeDetail').classList.add('open');}
function closeNoticeDetail(e){if(e&&e.target&&e.target.closest('.modal'))return;document.getElementById('noticeDetail').classList.remove('open');}

document.addEventListener('DOMContentLoaded',async()=>{document.getElementById('year').textContent=new Date().getFullYear();try{DATA=await loadDataFromDB();}catch(e){DATA=await loadData();}renderSiteContent();renderNotices();showLatestNoticePopup();const hash=window.location.hash.replace('#','');if(hash&&document.getElementById('page-'+hash))showPage(hash);});
